### ISSUE TITLE
How to use `ClipperOffset` with Double coordinates, and get the right solution in Double?

### ISSUE THREAD

**Issue by istinnstudio** [micycle1/Clipper2-java#1]
Hi, it is nice to see this library on java...  thanks!
I am trying to find out how to use OFFSET --> clipper2.offset.ClipperOffset()
So far I can see there is support for Long 64bit integers and some kind of "normalized" Double variables.
I have made some brutal modifications to source in order to get some results for my project... luckily it seems work with some polygon overlapping, deleted points issues due to some kind of precision reduction along the data path, but I guess there are  better and safer ways to do this in Double coordinates.
All points should have Double precision coordinates and this has to remain in the solution apparently.

this is a simple example "ported" from v1 of c# but I am not sure if this is the right way to get a right result/solution.
This seem to work for me (specific use, not tested other ways) with a lot of brutal hacks in source replacing path64 references with pathD. This is obviously wrong but it works for now. The question is, is there an example that can use Double coordinates, and get a right solution apparently in Double?

this code is just for reference, will not work as it is
  ```
   static public clipper2.core.PathD doOffsetMethodClipper2 (clipper2.core.PathD p, double offset_nm)
    {
       System.out.println("INSIDE DO OFFSET IN CLIPPER 2 !");
// what is p
// we will feed -->  PathD p with raw point Double precision coordinates
        // Offset
        clipper2.core.PathsD solution = new clipper2.core.PathsD(); // how to get the solution?
       clipper2.offset.ClipperOffset co = new clipper2.offset.ClipperOffset();


        co.AddPath(p, JoinType.Miter, EndType.Polygon);   // add pathD

// see if we have at least 3 valid points for polygons
        System.out.println("See POINT 0 DoOffset X --> "+p.get(0).getX()); // added getter-setter in source
        System.out.println("See POINT 0 DoOffset Y --> "+p.get(0).getY());      
        System.out.println("See POINT 1 DoOffset X --> "+p.get(1).getX());
        System.out.println("See POINT 1 DoOffset Y --> "+p.get(1).getY());        
        System.out.println("See POINT 2 DoOffset X --> "+p.get(2).getX());
        System.out.println("See POINT 2 DoOffset Y --> "+p.get(2).getY());

.
      //  co.setReverseSolution(true);     // parameters   
       // co.setArcTolerance(0.1);     // parameters   
       // co.Execute( offset_nm);

        co.ExecuteD( offset_nm); // brutal lot of modifications in several places in order to get PathD support (how to use Long normalization?)
//co.execute(solutions, offset_nm); // the old v1 execute

// SOMETHING LIKE clipper2.Clipper.InflatePaths HERE? solution = clipper2.Clipper.InflatePaths ...
        clipper2.core.PathsD pths = new clipper2.core.PathsD();
        pths.add(p);

       solution = clipper2.Clipper.InflatePaths(pths, offset_nm, JoinType.Miter, EndType.Polygon);   // new for v2
       return   solution.get(0); // to a loop in order to construct path2D shapes

       } 
```
So, if there is an example in the right way this "offset" is supposed to be used, that would be useful...

**Comment by micycle1** [comment]
So your question is about improving precision during clipping (specifically offsetting) operations?

> In Clipper2 there are now two Clipper classes - Clipper64 and ClipperD. Clipper64 as it's name implies, supports 64bit integer coordinates, whereas ClipperD supports double float coordinates. Nevertheless, to ensure numerical robustness, **Clipper2 still performs all clipping operations on signed 64bit integer coordinates internally**. Because of this, the floating point coordinates accepted by ClipperD objects will be converted into integers using the floating point precision specified in ClipperD's constructor.


To get improve precision, you should scale the decimal coordinates using `Clipper.ScalePathsD(paths, precision)`, then perform the offset with an offset value=`offset*precision`, then apply `Clipper.ScalePathsD(solution, 1/precision)` to the (scaled up) solution to get a high-precision solution having the correct scale.

**Comment by istinnstudio** [comment]
Great answer, with your guidance I have just realized that the precision parameter is already there in Clipper
So  just using...

```
              // offset polygon
  solution = clipper2.Clipper.InflatePaths(pths, offset_nm, JoinType.Miter, EndType.Polygon, 25, 8); 
```
The parameter has values between -8 and 8 --> "the Double 16 digits"

in Clipper.java
```
public static PathsD InflatePaths(PathsD paths, double delta, JoinType joinType, EndType endType, double miterLimit, int precision) {
		if (precision < -8 || precision > 8) {
			throw new IllegalArgumentException("Error: Precision is out of range.");
		}
```
now shapes are perfect
thank you !!!
