### ISSUE TITLE
Offset gets scrambled when using union + inflate on complex overlapping polygons when using precision >6

### ISSUE THREAD

**Issue by istinnstudio** [micycle1/Clipper2-java#14]
I am not sure this is a bug or a fault on my side yet, it takes place when offsetting complex overlapping polygons using union (winding rules used). According to the clipper2 official documentation:
https://angusj.com/clipper2/Docs/Units/Clipper.Offset/Classes/ClipperOffset/_Body.htm
I have used both union and inflate to make a buffer zone across an overlapping polygon. The issue is that when using precision more than 6, the offset gets scrambled. 

 code goes like this: 
```
static public clipper2.core.PathD doOffsetMethodClipper2(clipper2.core.PathD p, double offset_nm) {
clipper2.core.PathsD solution = new clipper2.core.PathsD();
      if (offset_nm == 0) {
         return p;
      } else {
         clipper2.core.PathsD pths = new clipper2.core.PathsD();
         pths.add(p);
       pths = clipper2.Clipper.Union(pths, pths, FillRule.NonZero, 8); // UNION ON OVERLAPPING POLYGONS WITH PRECISION
       solution = clipper2.Clipper.InflatePaths(pths, offset_nm , JoinType.Miter, EndType.Polygon, 15, 8); // precision breaks results if >6 WHY?
...
}
```
pathD objects are being created from multi point overlapping  path2D using double coordinates and a series of conversion methods that all use double point2D.Double and path2D.Double
scrambled precision 8
![image](https://github.com/user-attachments/assets/8878bd03-3cdf-4d52-bc27-cf3f9d544bc1)
perfect precision 6
![image](https://github.com/user-attachments/assets/59388ceb-cd8e-4397-a4eb-4101d94de5e1)

setting precision to 6 everything looks normal. Looks like a float casting but I cannot find any of those in my coordinates. There could be some kind of precision reduction somewhere in the clipper, clipperD  class? Regards...

**Comment by istinnstudio** [comment]
I close the issue as I cannot reproduce it any more, complex polygons need excessive tests of method parameters on sequential spatial operations, solutions can go out of predictable space easily. Library do a fine job even for the most complex scenarios, clipper2 official documentation has to be studied, considering cases that can go out of control: https://angusj.com/clipper2/Docs/_Body.htm

**Comment by micycle1** [comment]
I'd seen your issue but hadn't yet go around to testing myself yet... Good to see you can't reproduce since it indicates very rare.

It's possible that it is bugged in some way though -- this Java version is based on v1.2.2 and there have been lots of (minor) bug fixes on the parent repository since then.
